// Comics
export const GET_COMIC_DETAILS_SUCCESS = 'GET_COMIC_DETAILS_SUCCESS';

export const GET_COMIC_SEARCH_SUCCESS = 'GET_COMIC_SEARCH_SUCCESS';

export const GET_COMIC_ISSUE_SUCCESS = 'GET_COMIC_ISSUE_SUCCESS';

export const GET_COMIC_INCLUDED_SUCCESS = 'GET_COMIC_INCLUDED_SUCCESS';

export const GET_COMIC_LIST_BY_PAGE_SUCCESS = 'GET_COMIC_LIST_BY_PAGE_SUCCESS';

export const GET_COMIC_LIST_BY_GENRE_SUCCESS = 'GET_COMIC_LIST_BY_GENRE_SUCCESS';

export const GET_AUTOCOMPLETE_COMIC_LIST = 'GET_AUTOCOMPLETE_COMIC_LIST';

export const CLEAR_AUTOCOMPLETE = 'CLEAR_AUTOCOMPLETE';

// All Pages
export const UPDATE_ALL_PAGES = 'UPDATE_ALL_PAGES';